version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2_2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_REGION=${AWS_REGION}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${PWD}/../harrys-data-warehouse/airflow/dags:/usr/local/airflow/dags
            - ${PWD}/../harrys-data-warehouse/airflow/plugins:/usr/local/airflow/plugins
            - ${PWD}/../harrys-data-warehouse/airflow/requirements:/usr/local/airflow/requirements
        ports:
            - "8085:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
            - ./config/.env.localrunner