version: '3.7'
services:
    webserver:
        image: amazon/mwaa-local:2_2
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Sequential
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_REGION}
            - AWS_REGION=${AWS_REGION}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${PWD}/../harrys-data-warehouse/airflow/dags:/usr/local/airflow/dags
            - ${PWD}/../harrys-data-warehouse/airflow/plugins:/usr/local/airflow/plugins
            - ${PWD}/../harrys-data-warehouse/airflow/requirements.txt:/usr/local/airflow/requirements/requirements.txt
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
