version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    resetdb:
        image: amazon/mwaa-local:2_4
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_REGION}
            - AWS_REGION=${AWS_REGION}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${HDW_AIRFLOW_ROOT}/dags:/usr/local/airflow/dags
            - ${HDW_AIRFLOW_ROOT}/plugins:/usr/local/airflow/plugins
            - ${HDW_AIRFLOW_ROOT}/requirements:/usr/local/airflow/requirements
            - ${HOME}/.aws:/usr/local/airflow/.aws
        ports:
            - "8083:8080"
        command: resetdb
